@echo off
echo PREPARANDO TODO PARA TU APK DE MR. PAN...
echo 1. Construyendo la web optimizada...
npm run build
echo 2. Sincronizando con Android...
npx cap sync
echo 3. Intentando abrir Android Studio...
npx cap open android
echo LISTO. Ahora en Android Studio ve a: Build - Build Bundle / APK - Build APK.
pause
